apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
  namespace: microshop
spec:
  provider:
    type: prometheus
    address: http://prometheus-operator.default:8080
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  service:
    port: 3000
    gateways:
      - microshop-gateway
    hosts:
      - microshop.local
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 30s
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s
