apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
  namespace: microshop
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  service:
    port: 3000
    gateways:
    - microshop-gateway.istio-system.svc.cluster.local
    hosts:
    - microshop.local
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 1m
    webhooks:
    - name: load-test
      type: pre-rollout
      url: http://flagger-loadtester.microshop/
      timeout: 5s
