apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microshop
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/devopspankaj77/microshop/frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^sha-[0-9a-f]{7}$
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/devopspankaj77/microshop/frontend:sha-abcdef1 # placeholder
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: microshop
  labels:
    app: backend
spec:
  selector:
    app: backend   # 👈 ye selector tere backend Deployment ke labels se match hona chahiye
  ports:
    - name: http
      port: 8080        # 👈 ClusterIP pe ye port expose hoga
      targetPort: 8080  # 👈 Pod ka containerPort jo tu Deployment me diya hai
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: microshop
  labels:
    app: backend
spec:
  selector:
    app: backend   # 👈 ye selector tere backend Deployment ke labels se match hona chahiye
  ports:
    - name: http
      port: 8080        # 👈 ClusterIP pe ye port expose hoga
      targetPort: 8080  # 👈 Pod ka containerPort jo tu Deployment me diya hai
  type: ClusterIP
