apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microshop
  annotations:
    # ArgoCD Image Updater config
    argocd-image-updater.argoproj.io/image-list: frontend=ghcr.io/devopspankaj77/microshop/frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Agar private hoti to secret use karna padta, abhi public hai to comment rehne do
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: frontend
          # 👇 Yahan ab tag ki jagah digest use hoga (ArgoCD Image Updater fill karega)
          image: ghcr.io/devopspankaj77/microshop/frontend@sha256:dummy
          ports:
            - containerPort: 3000
