apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret        # 2 spaces indent
  namespace: microshop      # 2 spaces indent
stringData:                 # 2 spaces indent
  MYSQL_ROOT_PASSWORD: "change-me-root"   # 2 spaces indent
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: "change-me-app"
